### ISSUE TITLE
REDIAL model

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/sars-cov-2-chemspace#4]
Hi @GemmaTuron ,

As agreed, we should check the REDIAL model (or any other SARS-CoV-2 model that we have in the hub) and run it in our chemical spaces.

**Comment by GemmaTuron** [comment]
These are run (see /data folder) but until we have the target information it does not make much sense to look into it too deeply

**Comment by miquelduranfrigola** [comment]
Thanks. Ideally, we should run REDIAL on:

- [ ] DrugBank (baseline)
- [ ] Our manually curated synthetic compounds
- [ ] Our manually curated natural products
- [ ] Our expanded list of compounds from CHEESE
- [ ] ChemDiv Coronavirus library

**Comment by miquelduranfrigola** [comment]
@GemmaTuron what is the status of this?

**Comment by GemmaTuron** [comment]
We need to delete the cheese compounds that are no longer part of the dataset (because the source molecule was duplicate, or not correctly labelled etc). I also need to re run it on the last set of hopefully final source data.

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron - let's just be careful with the deletion of CHEESE results since we also have DrugBank search outputs there now.

**Comment by GemmaTuron** [comment]
This is now completed and updated!
