### ISSUE TITLE
New molecules missing from cheese

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/sars-cov-2-chemspace#5]
Hello @miquelduranfrigola 

With so many changes in the source data is difficult to keep track of what are the correct files. I have cleaned up the Cheese results but these two inchikeys seem to be missing:
['VJEMOEYSQDKAQF-JDRYWMLESA-N', 'YTZALCGQUPRCGW-MXVXOLGGSA-N']

Can you check?

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron have these been included?

**Comment by GemmaTuron** [comment]
they are now included, I will close this issue
