### ISSUE TITLE
The `all_molecules.csv` file is not there anymore

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/sars-cov-2-chemspace#6]
Hi @GemmaTuron in the current version of the repository the `all_molecules.csv` file is not there anymore. Instead, we have a `v1` and a `v0`. Can we decide on a single file and name it `all_molecules.csv` again? Many thanks!

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 

The all_molecules.csv will be the final version but I still need to work on that to ensure we have the final set of molecules. V0 is the first set we had and V1 is the latest, but it contained many duplicates. Please wait until I have had time to sort out the issues with the source data from Fidele. The last push was clearly labelled as WIP

**Comment by GemmaTuron** [comment]
I will delete the previous versions and keep only the final data as all_molecules.csv
